use windows_sys::Win32::System::Ioctl::{FILE_ANY_ACCESS, METHOD_BUFFERED, METHOD_NEITHER};

use kernel_macros::CTL_CODE;

pub const IOCTL_DELPROTECT_ADD_EXE_UTF8: u32 =
    CTL_CODE!(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub const IOCTL_DELPROTECT_ADD_EXE_UTF16: u32 =
    CTL_CODE!(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub const IOCTL_DELPROTECT_REMOVE_EXE_UTF8: u32 =
    CTL_CODE!(0x8000, 0x8012, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub const IOCTL_DELPROTECT_REMOVE_EXE_UTF16: u32 =
    CTL_CODE!(0x8000, 0x8012, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub const IOCTL_DELPROTECT_CLEAR: u32 = CTL_CODE!(0x8000, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS);
